import { wrap } from "@mikro-orm/core";
import { NextApiRequest, NextApiResponse } from "next"
import { DataBase } from "../../../../server/connectors"
import { Blog } from "../../../../src/components/types";
import type { ResponseError, ResponseSuccess } from "../../../../src/api"
import { ObjectId } from "@mikro-orm/mongodb";

export default async function handler(req: NextApiRequest, res: NextApiResponse) {
  try {
    if (req.method !== 'POST') {
      throw new Error("Only POST method available")
    }
  
    const db = new DataBase();
    await db.init();
    const dto: Blog.Post & { id: string } = JSON.parse(req.body);

    /** autogenerated values */
    delete dto.dateCreated;
    delete dto.dateUpdated;

    const repo = db.getRepo(db.entities.Post)
    let post = await repo.findOne({ _id: new ObjectId(dto.id) });

    if (!post) {
      post = new db.entities.Post();
    }
    
    wrap(post).assign(dto);
    await repo.persistAndFlush(post);

    const response: ResponseSuccess<null> = {
      message:  "SUCCESS",
      data: null
    }
    res.json(response);
  } catch (e: any) {
    const response: ResponseError = {
      message: "ERROR",
      errors: [ e.message ]
    }
    res.status(400).json(response);
  }
}